CREATE TABLE "program_assignment_templates" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "name" text,
  "description" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "workout_assignment_templates" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "program_template_id" int,
  "program_day" int,
  "workout_position" int,
  "name" text,
  "description" text,
  "notes" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "circuit_assignment_templates" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "workout_templates_id" int,
  "circuit_position" int,
  "sets" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "exercise_assignment_templates" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "circuit_assignment_id" int,
  "exercise_id" int,
  "exercise_position" int,
  "sets" int,
  "reps" int,
  "weight" float,
  "percentage_of_e1rm" float,
  "percentage_of_last_set" float,
  "adjusted_weight" float,
  "rpe_target" int,
  "amrap" bool DEFAULT false,
  "amsap" bool DEFAULT false,
  "time_limit" int,
  "rest_period" int DEFAULT 180,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "program_assignments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "program_assignment_templates_id" int,
  "user_id" int,
  "coach_id" int,
  "name" text,
  "description" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "workout_assignments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "coach_id" int,
  "program_id" int,
  "workout_assignment_template_id" int,
  "workout_date" date,
  "workout_position" int,
  "name" text,
  "description" text,
  "notes" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "circuit_assignments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workout_assignment_id" int,
  "circuit_assignment_template_id" int,
  "circuit_position" int,
  "sets" int
);

CREATE TABLE "exercise_assignments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "circuit_assignment_id" int,
  "exercise_assignment_template_id" int,
  "exercise_id" int,
  "exercise_position" int,
  "sets" int,
  "reps" int,
  "weight" float,
  "percentage_of_e1rm" float,
  "percentage_of_last_set" float,
  "adjusted_weight" float,
  "rpe_target" int,
  "amrap" bool DEFAULT false,
  "amsap" bool DEFAULT false,
  "duration" int,
  "rest_period" int DEFAULT 180
);

CREATE TABLE "exercise_results" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "exercise_assignment_id" int,
  "actual_exercise_id" int,
  "actual_sets" int,
  "actual_reps" int,
  "actual_weight" float,
  "actual_rpe" int,
  "actual_duration" timestamp,
  "notes" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "exercises" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text,
  "difficulty" varchar,
  "created_at" timestamp
);

CREATE TABLE "exercise_substitutes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "exercise_id" int,
  "substitute_exercise_id" int
);

CREATE TABLE "e1rm_history" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "exercise_id" int,
  "e1rm" float,
  "calculated_at" timestamp
);

CREATE TABLE "personal_bests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "exercise_id" int,
  "rep_range" int,
  "weight" float,
  "achieved_at" timestamp
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE,
  "password_hash" varchar,
  "role" varchar,
  "created_at" timestamp
);

CREATE TABLE "coach_user_relation" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "coach_id" int,
  "user_id" int,
  "start_date" date,
  "end_date" date,
  "status" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "tokens" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "token" varchar,
  "created_at" timestamp,
  "expires_at" timestamp
);

ALTER TABLE "program_assignment_templates" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "workout_assignment_templates" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "workout_assignment_templates" ADD FOREIGN KEY ("program_template_id") REFERENCES "program_assignment_templates" ("id");

ALTER TABLE "circuit_assignment_templates" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "circuit_assignment_templates" ADD FOREIGN KEY ("workout_templates_id") REFERENCES "workout_assignment_templates" ("id");

ALTER TABLE "exercise_assignment_templates" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "exercise_assignment_templates" ADD FOREIGN KEY ("circuit_assignment_id") REFERENCES "circuit_assignment_templates" ("id");

ALTER TABLE "exercise_assignment_templates" ADD FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "program_assignments" ADD FOREIGN KEY ("program_assignment_templates_id") REFERENCES "program_assignment_templates" ("id");

ALTER TABLE "program_assignments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "program_assignments" ADD FOREIGN KEY ("coach_id") REFERENCES "users" ("id");

ALTER TABLE "workout_assignments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "workout_assignments" ADD FOREIGN KEY ("coach_id") REFERENCES "users" ("id");

ALTER TABLE "workout_assignments" ADD FOREIGN KEY ("program_id") REFERENCES "program_assignments" ("id");

ALTER TABLE "workout_assignments" ADD FOREIGN KEY ("workout_assignment_template_id") REFERENCES "workout_assignment_templates" ("id");

ALTER TABLE "circuit_assignments" ADD FOREIGN KEY ("workout_assignment_id") REFERENCES "workout_assignments" ("id");

ALTER TABLE "circuit_assignments" ADD FOREIGN KEY ("circuit_assignment_template_id") REFERENCES "circuit_assignment_templates" ("id");

ALTER TABLE "exercise_assignments" ADD FOREIGN KEY ("circuit_assignment_id") REFERENCES "circuit_assignments" ("id");

ALTER TABLE "exercise_assignments" ADD FOREIGN KEY ("exercise_assignment_template_id") REFERENCES "exercise_assignment_templates" ("id");

ALTER TABLE "exercise_assignments" ADD FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "exercise_results" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "exercise_results" ADD FOREIGN KEY ("exercise_assignment_id") REFERENCES "exercise_assignments" ("id");

ALTER TABLE "exercise_results" ADD FOREIGN KEY ("actual_exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "exercise_substitutes" ADD FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "exercise_substitutes" ADD FOREIGN KEY ("substitute_exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "e1rm_history" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "e1rm_history" ADD FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "personal_bests" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "personal_bests" ADD FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "coach_user_relation" ADD FOREIGN KEY ("coach_id") REFERENCES "users" ("id");

ALTER TABLE "coach_user_relation" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
