CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE,
  "password_hash" varchar,
  "role" varchar,
  "created_at" timestamp
);

CREATE TABLE "tokens" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "token" varchar,
  "created_at" timestamp,
  "expires_at" timestamp
);

CREATE TABLE "workouts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" int,
  "coach_id" int,
  "workout_date" date,
  "description" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "workout_assignments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workout_id" int,
  "exercise_id" int,
  "exercise_instance_id" int,
  "sets" int,
  "reps" int,
  "weight" float,
  "duration" int,
  "percentage_of_e1rm" float,
  "percentage_of_last_set" float,
  "adjusted_weight" float,
  "rpe_target" int,
  "exercise_order" int,
  "superset_group" int,
  "circuit_id" int,
  "amrap" bool DEFAULT false,
  "amsap" bool DEFAULT false,
  "time_limit" int,
  "rest_period" int DEFAULT 180,
  "modification_exercise_id" int,
  "notes" text,
  "created_at" timestamp
);

CREATE TABLE "workout_results" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workout_assignment_id" int,
  "sets_completed" int,
  "reps_completed" int,
  "weight_used" float,
  "rpe_actual" int,
  "notes" text,
  "created_at" timestamp
);

CREATE TABLE "exercise_modifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "exercise_id" int,
  "modification_exercise_id" int
);

CREATE TABLE "e1rm_history" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "exercise_id" int,
  "e1rm" float,
  "calculated_at" timestamp
);

CREATE TABLE "exercises" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text,
  "created_at" timestamp
);

CREATE TABLE "personal_bests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "exercise_id" int,
  "rep_range" int,
  "weight" float,
  "achieved_at" timestamp
);

CREATE TABLE "coach_client_relation" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "coach_id" int,
  "client_id" int,
  "start_date" date,
  "end_date" date,
  "status" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

ALTER TABLE "tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "workouts" ADD FOREIGN KEY ("client_id") REFERENCES "users" ("id");

ALTER TABLE "workouts" ADD FOREIGN KEY ("coach_id") REFERENCES "users" ("id");

ALTER TABLE "workout_assignments" ADD FOREIGN KEY ("workout_id") REFERENCES "workouts" ("id");

ALTER TABLE "workout_assignments" ADD FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "workout_assignments" ADD FOREIGN KEY ("modification_exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "workout_results" ADD FOREIGN KEY ("workout_assignment_id") REFERENCES "workout_assignments" ("id");

ALTER TABLE "exercise_modifications" ADD FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "exercise_modifications" ADD FOREIGN KEY ("modification_exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "e1rm_history" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "e1rm_history" ADD FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "personal_bests" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "personal_bests" ADD FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "coach_client_relation" ADD FOREIGN KEY ("coach_id") REFERENCES "users" ("id");

ALTER TABLE "coach_client_relation" ADD FOREIGN KEY ("client_id") REFERENCES "users" ("id");

ALTER TABLE "personal_bests" ADD FOREIGN KEY ("user_id") REFERENCES "personal_bests" ("id");
